<a href="https://colab.research.google.com/github/atharva7471/AthoFolioo/blob/main/Day29-SklearnPipelines/29_titanic_without_pipelines.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Titanic without using SK-pipelines

In [ ]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler
from sklearn.tree import DecisionTreeClassifier

In [ ]:
df = pd.read_csv('train.csv')

In [ ]:
df.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
376,377,1,3,"Landergren, Miss. Aurora Adelia",female,22.0,0,0,C 7077,7.2500,NaN,S
402,403,0,3,"Jussila, Miss. Mari Aina",female,21.0,1,0,4137,9.8250,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
240,241,0,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C
265,266,0,2,"Reeves, Mr. David",male,36.0,0,0,C.A. 17248,10.5000,NaN,S

In [ ]:
df.drop(columns=['PassengerId','Name','Ticket', 'Cabin'], inplace=True)

In [ ]:
df.sample(5)

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
758         0       3    male  34.0      0      0   8.0500        S
264         0       3  female   NaN      0      0   7.7500        Q
28          1       3  female   NaN      0      0   7.8792        Q
90          0       3    male  29.0      0      0   8.0500        S
604         1       1    male  35.0      0      0  26.5500        C

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']),
                                                    df['Survived'],
                                                    test_size=0.2,
                                                    random_state=42)

In [ ]:
X_train.sample(2)

     Pclass   Sex   Age  SibSp  Parch    Fare Embarked
586       2  male  47.0      0      0  15.000        S
267       3  male  25.0      1      0   7.775        S

In [ ]:
y_train.sample(2)

834    0
50     0
Name: Survived, dtype: int64

In [ ]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [ ]:
#Applying imputor class for age and embarked

si_age = SimpleImputer()
si_embarked = SimpleImputer(strategy='most_frequent')

X_train_age = si_age.fit_transform(X_train[['Age']])
X_test_age = si_age.fit_transform(X_test[['Age']])

X_train_Embarked = si_embarked.fit_transform(X_train[['Embarked']])
X_test_Embarked = si_embarked.fit_transform(X_test[['Embarked']])

In [ ]:
#One hot encoding for Sex and Embarked

ohe_Sex = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe_Embarked = OneHotEncoder(sparse_output=False, handle_unknown='ignore')

X_train_sex = ohe_Sex.fit_transform(X_train[['Sex']])
X_test_sex = ohe_Sex.fit_transform(X_test[['Sex']])

X_train_Embarked = ohe_Embarked.fit_transform(X_train_Embarked)
X_test_Embarked = ohe_Embarked.fit_transform(X_test_Embarked)

In [ ]:
X_train_sex

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       ...,
       [0., 1.],
       [1., 0.],
       [0., 1.]])

In [ ]:
X_train_Embarked

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [ ]:
X_train_rem = X_train.drop(columns=['Sex','Age', 'Embarked'])
X_test_rem = X_test.drop(columns=['Sex','Age', 'Embarked'])

In [ ]:
X_train_final = np.concatenate((X_train_rem, X_train_sex, X_train_age, X_train_Embarked), axis=1)
X_test_final = np.concatenate((X_test_rem, X_test_sex, X_test_age, X_test_Embarked), axis=1)

In [ ]:
print(X_test_final)
print(X_train_final.shape)

[[3. 1. 1. ... 1. 0. 0.]
 [2. 0. 0. ... 0. 0. 1.]
 [3. 0. 0. ... 0. 0. 1.]
 ...
 [3. 1. 5. ... 0. 0. 1.]
 [2. 0. 0. ... 0. 0. 1.]
 [3. 1. 1. ... 0. 0. 1.]]
(712, 10)

In [ ]:
clf = DecisionTreeClassifier()
clf.fit(X_train_final, y_train)

DecisionTreeClassifier()

In [ ]:
y_pred = clf.predict(X_test_final)

In [ ]:
y_pred

array([0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.7430167597765364

In [ ]:
import pickle

In [ ]:
pickle.dump(ohe_Sex, open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_Embarked, open('models/ohe_Embarked.pkl','wb'))
pickle.dump(clf, open('models/clf.pkl','wb'))